name: Deploy Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Create test application-secret.yml from GitHub Secret
        run: |
          mkdir -p ./src/test/resources
          cat <<EOF >  ./src/test/resources/application-secret.yml
          ${{ secrets.TEST_APPLICATION_SECRET_YML }}
          EOF
        shell: bash

      - name: Create main application-secret.yml from GitHub Secret
        run: |
          mkdir -p ./src/main/resources
          cat <<EOF >  ./src/main/resources/application-secret.yml
          ${{ secrets.DEV_APPLICATION_SECRET_YML }}
          EOF
        shell: bash

      - name: Create firebase-service-account.json from GitHub Secret
        run: |
          cat <<EOF >  ./src/main/resources/firebase-service-account.json
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          EOF
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Test And Build
        run: ./gradlew build --no-daemon